export { apiSlice } from './apiSlice';
export { tagTypes } from './apiSlice';

// Export all hooks
export {
  useLoginMutation,
  useRegisterMutation,
  useRefreshTokenMutation,
  useLogoutMutation,
  useGetProfileQuery,
  useUpdateProfileMutation,
  useUpdatePreferencesMutation,
  useGetTasksQuery,
  useGetTaskByIdQuery,
  useCreateTaskMutation,
  useUpdateTaskMutation,
  useDeleteTaskMutation,
  useGetSessionsQuery,
  useGetSessionByIdQuery,
  useCreateSessionMutation,
  useStartSessionMutation,
  usePauseSessionMutation,
  useCompleteSessionMutation,
  useGetTeamsQuery,
  useGetTeamByIdQuery,
  useCreateTeamMutation,
  useJoinTeamMutation,
  useLeaveTeamMutation,
  useGetAchievementsQuery,
  useGetUserAchievementsQuery,
  useUnlockAchievementMutation,
  useGetChallengesQuery,
  useGetChallengeByIdQuery,
  useCreateChallengeMutation,
  useJoinChallengeMutation,
  useUpdateChallengeProgressMutation,
  useGetFocusAnalyticsQuery,
  useGetWellnessAnalyticsQuery,
  useGetTeamAnalyticsQuery,
  useGetNotificationsQuery,
  useMarkNotificationAsReadMutation,
  useMarkAllNotificationsAsReadMutation,
} from './apiSlice';